feat: add-bookings initial
akrecev/java-shareit pull request #2
Opened 2023-02-07 21:24 UTC by akrecev

2023-02-08 19:51 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-02-08 19:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    @NotNull(groups = {Update.class})
Как то не там у тебя `Update` установлен.
Никто, как правило, `id` не обновляет у сущностей!

Да и если проследить за использованием Update, то видно что он ни к месту.
Для этой сущности нет валидации по Update, а для сущности пользователя нет полей отмеченных как Update.

Пересмотри... и или правильно примени или удали...

2023-02-08 19:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "start_date")
Не отмечены все особенности полей, которые присутствуют в БД.
Например то что все поля `NOT NULL` -> `nullable = false`

2023-02-08 19:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("select b from Booking b " +
Оформляй запросы, набирая команды SQL в верхнем регистре: SELECT

2023-02-08 19:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/sevice/BookingServiceImpl.java
> +        }
Мои советы по оформлению кода. Сразу пример, потом пояснения:

``` 
        ..................
        booking.setStatus(Status.WAITING);

        if (userId.equals(item.getOwner().getId())) {
            throw new DataNotFoundException("User id=" + userId);
        }

        if (!item.getAvailable()) {
            throw new BadRequestException("Item id=" + item.getId() + " not available");
        }

        Booking saved = bookingRepository.save(booking);
        
        return toBookingDtoResponse(saved);
    }
```

- держим обособлено проверки которые кидают исключения, их так лучше видно!
- одно из условия я инвертировал и избавился от лишней вложенности else
- главное действие - сохранение вынес на отдельную строку. Не прячем главное действие где то среди других строк.
- перед return делаем отступ - пустая строка. Чтобы визуально отделить окончание метода

2023-02-08 19:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/sevice/BookingServiceImpl.java
> +        throw new DataNotFoundException("User id= " + userId);
У тебя же метод findUser подразумевает проверку, зачем код на 59 строке?

2023-02-08 19:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/booking/sevice/BookingServiceImpl.java
> +        return itemRepository.findById(itemId).orElseThrow(
Каждую новую операцию в цепочке на новую строку...

```
    private Booking findBooking(Long bookingId) {
        return bookingRepository.findById(bookingId)
                                .orElseThrow(() -> new DataNotFoundException("Booking Id=" + bookingId));
    }
```

2023-02-08 19:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private User find(Long id) {
Никогда мне не нравилось, когда это выносят в отдельный метод...
Практически нулевой выхлоп - заменять одну строку кода методом.
Но самое противное что это мешает строить правильный код!

Вот так, например, может выглядеть метод get

```
    @Override
    public UserDto get(Long id) {
        return userRepository.findById(id)
                             .map(UserMapper::toUserDto)
                             .orElseThrow(() -> new DataNotFoundException("id:" + id));
    }
```

2023-02-08 19:51 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
>      private String description;
Сущность не отражает реальности полей в БД.
Например, description -> VARCHAR(512) not null !

Делай отступы между полями.

2023-02-09 07:12 UTC, akrecev commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    @NotNull(groups = {Update.class})
Удалил разделение на Update  и Create. На данном этапе оно не используется. Поставил из того расчета что при обновлении должна приходить сущность с id. Но вызовы по другому построены и id приходит отдельно. При создании класса слишком рано проставил аннотации валидации на обновление.

2023-02-09 07:59 UTC, akrecev commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "start_date")
Добавил. Думал наоборот, если есть прописанные ограничения в таблицах БД, то незачем их дублировать в коде. Мы же не разрешаем хибернейту менять структуру БД.

2023-02-09 08:16 UTC, akrecev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    @Query("select b from Booking b " +
Согласен, так гораздо лучше, но почему-то в примере от  Практикума команды были в нижнем регистре. Поэтому сделал по аналогии.

2023-02-09 11:36 UTC, akrecev commented on src/main/java/ru/practicum/shareit/booking/sevice/BookingServiceImpl.java
> +        }
Да, согласен, так будет логичней и более читаемо. Поправил по аналогии во всех сервисах

2023-02-09 11:52 UTC, akrecev commented on src/main/java/ru/practicum/shareit/booking/sevice/BookingServiceImpl.java
> +        throw new DataNotFoundException("User id= " + userId);
Здесь идет проверка на то что запрос выполняет хозяин вещи или арендатор. Информацию о букинге только они имеют право запрашивать. Тип исключения конечно не подходящий. Но это согласно требований тестов, там нужна именно 404.
findUser убрал. проверка в if'е делает его излишним

2023-02-09 11:57 UTC, akrecev commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
>      private String description;
Да, добавил описания в аннотации

2023-02-09 13:04 UTC, akrecev commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private User find(Long id) {
Полностью согласен, но привык, что нужно избегать любое дублирование кода.

2023-02-09 13:09 UTC, akrecev commented on src/main/java/ru/practicum/shareit/booking/sevice/BookingServiceImpl.java
> +        return itemRepository.findById(itemId).orElseThrow(
Да, поправил.

2023-02-09 13:11 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private User find(Long id) {
Только не впадай в крайности ))

2023-02-09 13:55 UTC, akrecev commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private User find(Long id) {
Видимо впал)

2023-02-09 17:04 UTC, akrecev commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    private User find(Long id) {
Наверное стоит выделять в отдельный метод при 2-х и более повторениях и если нельзя встроить конструкцию в часть другого кода, как в твоем примере. Как правильно?

2023-02-09 18:03 UTC, FanaticFiz approved these changes

2023-02-09 20:21 UTC, merged